cart/urls.py
from django.urls import path
from cart.views import CartView, IncreaseQuantityView, ProductDetailView
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),

]

vinylMain/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from coreLogic import views
from coreLogic.views import ContactView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.shortcuts import reverse


User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100)
    

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    

class Address(models.Model):
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=150)
    address_line_2 = models.CharField(max_length=150)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.address_line_1}, {self.address_line_2},{self.city},"
    
    class Meta:
        verbose_name_plural = 'Addresses'
    

class FormatVariation(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    
class Product(models.Model):
    artist_name = models.CharField(max_length=150, null=False)
    album_title = models.CharField(max_length=150, null=False)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='product_images')
    image_2 = models.ImageField(upload_to='product_images')
    price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    available_formats = models.ManyToManyField(FormatVariation)
    primary_category = models.ForeignKey(Category,
                                        related_name='primary_products',
                                        on_delete=models.CASCADE)
    secondary_category = models.ManyToManyField(Category, blank=True)
    
    def __str__(self):
        return self.artist_name

    def get_absolute_url(self):
        return reverse("cart:product-detail", kwargs={"slug": self.slug})
    
    def get_update_url(self):
        return reverse("staff:product-update", kwargs={"pk": self.pk})
    
    def get_delete_url(self):
        return reverse("staff:product-delete", kwargs={"pk": self.pk})
        
    def get_price(self):
        return "{:.2f}".format(self.price / 100)
    

class OrderItem(models.Model):
    order = models.ForeignKey("Order", related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    format = models.ForeignKey(FormatVariation, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.product.artist_name} / {self.product.album_title} - {self.quantity}x"

    def get_raw_total_item_price(self):
        return self.quantity * self.product.price 
    
    def get_total_item_price(self):
        price = self.get_raw_total_item_price()
        return "{:.2f}".format(price / 100)


class Order(models.Model):
    user = models.ForeignKey(User,
                            blank=True,
                            null=True,
                            on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    
    billing_address = models.ForeignKey(Address,
                                        related_name='billing_address',
                                        blank=True,
                                        null=True,
                                        on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(Address,
                                        related_name='shipping_address',
                                        blank=True,
                                        null=True,
                                        on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"
    
    def get_raw_subtotal(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
        return total
    
    def get_subtotal(self):
        subtotal = self.get_raw_subtotal()
        return "{:.2f}".format(subtotal / 100)
    
    def get_raw_total(self):
        delivery = "-10%"
        subtotal = self.get_raw_subtotal()
        # #TODO: Add delivery charges
        # total = subtotal - delivery
        return subtotal
    
    def get_total(self):
        total = self.get_raw_total()
        return "{:.2f}".format(total / 100)
    
    
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='payments')
    payment_method = models.CharField(max_length=20, choices=(
        ('PayPal', 'PayPal'),
    ))
    timestamp = models.DateTimeField(auto_now_add=True)
    successful = models.BooleanField(default=False)
    amount = models.FloatField()
    raw_response = models.TextField()
    
    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"
    
    
def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.album_title)
   
pre_save.connect(pre_save_product_receiver, sender=Product)     
        

cart/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import FormatVariation, OrderItem, Product, Address


User = get_user_model()


class AddToCartForm(forms.ModelForm):
    format = forms.ModelChoiceField(queryset=FormatVariation.objects.none())

    class Meta:
        model = OrderItem
        fields = ['quantity', 'format']

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=product_id)
        super().__init__(*args, **kwargs)

        self.fields['format'].queryset = product.available_formats.all()


class AddressForm(forms.Form):
    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    # selected_billing_address = forms.ModelChoiceField(
    #     Address.objects.none(), required=False
    # )

    street_name_and_number = forms.CharField(required=False)
    town_or_city = forms.CharField(required=False)
    county = forms.CharField(required=False)
    postcode = forms.CharField(required=False)
    # billing_address_1 = forms.CharField()
    # billing_address_2 = forms.CharField()
    # billing_zip_code = forms.CharField()
    # billing_city = forms.CharField()

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        # user = User.objects.get(id=user_id)

        shipping_address_queryset = Address.objects.filter(
            # user=user,
            address_type='S'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_queryset

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('street_name_and_number', None):
                self.add_error("street_name_and_number",
                               "Please fill in this field")
            if not data.get('town_or_city', None):
                self.add_error("town_or_city", "Please fill in this field")
            if not data.get('county', None):
                self.add_error("county", "Please fill in this field")
            if not data.get('postcode', None):
                self.add_error("postcode", "Please fill in this field")

        # selected_billing_address = data.get('selected_billing_address', None)
        # if selected_billing_address is None:
        #     if not data.get('billing_address_1', None):
        #         self.add_error("street_name_and_number", "Please fill in this field")
        #     if not data.get('billing_address_2', None):
        #         self.add_error("town_or_city", "Please fill in this field")
        #     if not data.get('billing_zip_code', None):
        #         self.add_error("county", "Please fill in this field")
        #     if not data.get('billing_city', None):
        #         self.add_error("postcode", "Please fill in this field")

cart/views.py
import datetime
import json
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views import generic
from .forms import AddToCartForm, AddressForm
from .utils import get_or_set_order_session
from .models import (Product,
                     OrderItem,
                     Address,
                     Payment,
                     Order,
                     Category)


class ProductListView(generic.ListView):
    template_name = 'cart/product_list.html'

    def get_queryset(self):
        qs = Product.objects.all()
        category = self.request.GET.get('category', None)
        if category:
            qs = qs.filter(Q(primary_category__name=category) |
                           Q(secondary_category__name=category)).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context


class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            format=form.cleaned_data['format']
        )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(generic.TemplateView):
    template_name = "cart/cart.html"

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect('cart:summary')


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect('cart:summary')


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect('cart:summary')


class CheckoutView(generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get(
            'selected_shipping_address')
        selected_billing_address = form.cleaned_data.get(
            'selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                user=self.request.user,
                address_line_1=form.cleaned_data['street_name_and_number'],
                address_line_2=form.cleaned_data['town_or_city'],
                zip_code=form.cleaned_data['county'],
                city=form.cleaned_data['postcode'],
            )
            order.shipping_address = address

        # if selected_billing_address:
        #     order.billing_address = selected_billing_address
        # else:
        #     address = Address.objects.create(
        #         address_type='B',
        #         user=self.request.user,
        #         address_line_1=form.cleaned_data['billing_address_1'],
        #         address_line_2=form.cleaned_data['billing_address_2'],
        #         zip_code=form.cleaned_data['billing_zip_code'],
        #         city=form.cleaned_data['billing_city'],
        #     )
        #     order.billing_address = address
        order.save()
        messages.info(self.request, "Addresses added successfully")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(
            reverse("cart:thank-you"))
        return context


class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        print(body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({'data': 'success'})


class ThankYouView(generic.TemplateView):
    template_name = 'cart/thanks.html'


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'

templates/cart/cart.html
{% extends "product-detail-base.html" %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<body class="cart-body">
    <div style="width: 100%;" class="row">
        <div class="cart-product-detail-wrap col-md-6" data-aos="fade">
            {% for item in order.items.all  %}
            <div class="product-detail-box col-md-12">

                <a href="{% url 'cart:remove-from-cart' item.id %}" class="mb-4" style="text-align: center;">
                    <i class="material-icons" style="color: red;";>delete_forever</i>
                    <br>
                    Remove
                </a>

                <img src="{{ item.product.image_2.url }}" class="img-fluid cart-product-image" alt="Record Image">
                <div class="cart-product-albumtitle-wrap">
                    <div class="row product-info-wrap">
                        <p class="artist-name">{{ item.product.artist_name }}</p>
                        <p class="album-title">{{ item.product.album_title }}</p>
                        <p class="main-item-price">£{{ item.product.get_price }}</p>
                        <p class="album-title" style="color: red;">{{ item.format.name }}</p>
                    </div>

                    <span class="row justify-content-center mb-0">
                        <small class="quantity">Quantity</small>
                    </span>
                    <div class="input-group product-quantity mb-3">
                        <div class="input-group-prepend">
                            <a href="{% url 'cart:decrease-quantity' item.id %}"
                                class="minus-btn">
                                <i class="material-icons quantity-icons">arrow_drop_down</i>
                            </a>
                        </div>
                        <input type="text" class="form-control quantity-input text-center" value="{{ item.quantity }}">
                        <div class="input-group-append">
                            <a href="{% url 'cart:increase-quantity' item.id %}"
                                class="minus-btn">
                                <i class="material-icons quantity-icons">arrow_drop_up</i>
                            </a>
                        </div>
                    </div>
                    <p class="item-price">Product Total: <strong>£{{ item.get_total_item_price }}</strong></p>
                </div>
            </div>
            {% empty %}

            <div class="empty-cart">
                <p class="empty-cart-text">Your cart is empty.</p>
                <div class="sad-face-wrap">
                    <img src="{% static '/images/sad.png' %}" alt="sad face" class="sad1 sad-face-img">
                    <img src="{% static '/images/saddark.png' %}" alt="sad face" class="sad2 sad-face-img">
                    <img src="{% static '/images/sad.png' %}" alt="sad face" class="sad1 sad-face-img">
                    <img src="{% static '/images/saddark.png' %}" alt="sad face" class="sad2 sad-face-img">
                    <img src="{% static '/images/sad.png' %}" alt="sad face" class="sad1 sad-face-img">
                    <img src="{% static '/images/saddark.png' %}" alt="sad face" class="sad2 sad-face-img">
                </div>
                <a href="{% url 'cart:product-list' %}" class="mt-4 visit-store-text">Visit the store</a>
            </div>


            {% endfor %}
        </div>
        <div style="padding: 0;" class="col-md-6 cart-product-checkout-wrap" data-aos="fade">
            {% if order.items.count > 0 %}
            <div class="col-md-12 cart-product-checkout ">
                <h3 class="grand-total-text flexed mb-4">C A R T<span class="dotdotdots" style="visibility: hidden;">...</span>T O T A L</h3>
                <div class="totals-wrap ">
                    <p class="subtotal-total-text">
                        Subtotal
                        <span>£{{ order.get_subtotal }}</span>
                    </p>
                    <p class="complete-total-text">
                        Complete Total
                        <span>£{{ order.get_total }}</span>
                    </p>
                </div>
                <a href="{% url 'cart:product-list' %}" class="back-to-store-btn mt-4">Continue Browsing</a>
                <a href="{% url 'cart:checkout' %}" class="back-to-store-btn mt-4">Checkout</a>
            </div>

            {% endif %}
        </div>
    </div>
</body>


{% endblock content %}

templates/cart/payment.html
{% extends "product-detail-base.html" %}

{% block content %}

<!-- Loader Styles -->
<style>
    .lds-ripple {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
    }

    .lds-ripple div {
        position: absolute;
        border: 4px solid #000;
        opacity: 1;
        border-radius: 50%;
        animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
    }

    .lds-ripple div:nth-child(2) {
        animation-delay: -0.5s;
    }

    @keyframes lds-ripple {
        0% {
            top: 36px;
            left: 36px;
            width: 0;
            height: 0;
            opacity: 1;
        }

        100% {
            top: 0px;
            left: 0px;
            width: 72px;
            height: 72px;
            opacity: 0;
        }
    }
</style>


{% include "navbar.html" %}

<div style="width: 100%;" class="row paypal-btn-wrap mt-4 justify-content-center">
    <div style="width: 100%;" class="col-md-4">

        <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
            Payment Successfull
        </div>
        <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
            <span style="color: red;">Payment Falied</span>
        </div>

        <!-- Loader -->
        <div style="height: 100%; width: 100%;" class="text-center">
            <div id="loader" style="margin: auto; display: none;" class="lds-ripple">
                <div></div>
                <div></div>
            </div>
        </div>

        <!-- Payment info -->
        <div id="paymentInfo">
            <p>Order total: £{{ order.get_total }}</p>
            <h4>Select a payment method</h4>
            <div id="paypal-button-container"></div>
        </div>
    </div>

</div>

{% endblock content %}


{% block scripts %}
<script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}">
</script>
<script>
    const loader = document.getElementById('loader');
    const paymentInfo = document.getElementById('paymentInfo');

    function toggleLoader(on) {
        loader.style.display = on === true ? "block" : "none";
        paymentInfo.style.display = on === true ? "none" : "block";
    }


    // Paypal payments
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');


    // Sends request to "confirmOrderView"
    function sendOrderConfirmed(details) {
        return fetch("{% url 'cart:confirm-order' %}", {
            method: "post",
            body: JSON.stringify(details),
            headers: {
                "content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            }
        })
    }

    paypal.Buttons({
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '{{ order.get_total }}'
                    }
                }]
            });
        },
        onApprove: function (data, actions) {
            toggleLoader(true);
            // This function captures the funds from the transaction.
            return actions.order.capture().then(function (details) {
                    console.log(details);
                    sendOrderConfirmed(details).then(res => {
                        toggleLoader(false);
                        const alertSuccess = document.getElementById('alertSuccess');
                        alertSuccess.style.display = 'block';
                        setTimeout(() => {
                            window.location.replace("{{ CALLBACK_URL }}")
                        }, 1000);
                    })

                })
                .catch(err => {
                    const alertFailure = document.getElementById('alertFailure');
                    alertFailure.style.display = 'block';
                })
                .finally(() => toggleLoader(false));
        }
    }).render('#paypal-button-container');
</script>
{% endblock scripts %}

templates/cart/product_detail.html
{% extends "product-detail-base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'product-detail-navbar.html' %}

<body class="product-detail-body">

    <div class="row mt-4 product-container">

        <div class="col-md-6 product-image-box" data-aos="fade">
            <a href="{% url 'cart:product-list' %}" class="flexed back-arrow">⟵</a>
            <img src="{{ product.image_2.url }}" class="img-fluid product-detail-image">
            <form method="POST" class="product-quantity">

            </form>
        </div>

        <form method="POST" class="col-md-6 product-detail-box" data-aos="fade">
            {% csrf_token %}
            <div class="row product-details-wrap">
                <p class="product-detail-name">{{product.artist_name}}</p>
                <p class="product-detail-album mb-5">{{product.album_title}}</p>
                {{ form|crispy }}
            </div>


            <div class="button-row row">
                <div class="col-md-12 btn-wrap buy-btn" style="padding: 0px">
                    <button type="submit" class="main-btn-style">+ ADD TO CART</button>
                </div>
            </div>
        </form>
    </div>

</body>
{% endblock content %}

templates/cart/product_list.html
{% extends "base.html" %}


{% block content %}

<div class="scrollBar1"><span></span></div>
<div class="scrollBar2"><span></span></div>

<body class="product-list-body">
    <div class="col-md-12 mb-4 p-0 categories-wrap">
        
        <ul class="categories-list flexed">
            <h3 class="genres-title m-0 flexed">Genres ⟶</h3>
            {% for category in categories  %}
            <li class="category-list-item flexed">
                <a href="?category={{ category.name }}" class="d-flex">
                 

                    <span>{{ category.name }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <hr />
    <div class="row mb-3 all-product-wrap">
        {% for product in object_list  %}
        <div class="col-lg-3 col-md-5 product-wrap" data-aos="fade-up">

            <div class="lineDiv1" data-aos="fade-up" data-aos-delay="200"></div>

            <figure class="block-4-image">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" alt="Album image" class="product-image">
                </a>
            </figure>
            <div class="block-4-text p-4">
                <a href="{{ product.get_absolute_url }}">
                    <h3 class="artists-name">{{ product.artist_name }}</h3>
                </a>
                <p class="album-name">{{ product.album_title }}</p>
                <p class="album-name mt-4">£{{ product.get_price }}</p>

            </div>
            <div class="lineDiv2" data-aos="fade-up" data-aos-delay="200"></div>
        </div>
        {% endfor %}
    </div>
</body>



{% endblock content %}

templates/cart/thanks.html
{% extends "base.html" %}


{% block content %}


Thanks
  
{% endblock content %}