cart/urls.py
from django.urls import path
from cart.views import CartView, IncreaseQuantityView, ProductDetailView
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),

]

staff/urls.py
from django.urls import path
from . import views


app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<pk>/update/',
         views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/',
         views.ProductDeleteView.as_view(), name='product-delete'),


]

vinylMain/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from coreLogic import views
from coreLogic.views import ContactView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms
from cart.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'artist_name',
            'album_title',
            'slug',
            'image',
            'image_2',
            'price',
            'available_formats',
            'primary_category',
            'secondary_category',
        ]

staff/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django .shortcuts import reverse
from django.views import generic
from cart.models import Order, Product
from .mixins import StaffUserMixin
from .forms import ProductForm


class StaffView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered = True).order_by('-ordered_date')
    paginate_by = 20
    context_object_name = 'orders'


class ProductListView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 20
    context_object_name = 'products'


class ProductCreateView(LoginRequiredMixin, StaffUserMixin, generic.CreateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")


    def form_valid(self, form):
        form.save()
        return super(ProductUpdateView, self).form_valid(form)


class ProductDeleteView(LoginRequiredMixin, StaffUserMixin, generic.DeleteView):
    template_name = 'staff/product_delete.html'
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")

templates/staff/product_create.html
{% extends "no_header_base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="site-section">
    <div class="container">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}" class="back-to-staff-btn">⟵ Back to Staff Portal</a>
                <hr >
                <h4>Add to inventory</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="destroy-btn">Add/Update Product</button>
                </form>
            </div>
    </div>

    {% endblock content %}

templates/staff/product_delete.html
{% extends "no_header_base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="site-section">
    <div class="container">
            <div class="flexed col-md-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="destroy-btn">Complete Destruction!</button>
                </form>
            </div>
    </div>

    {% endblock content %}

templates/staff/product_list.html
{% extends "no_header_base.html" %}


{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff portal - Products</h2>
                <a class="add-inventory-btn" href="{% url 'staff:product-create' %}">+ Add inventory</a>
                <div class="card product-list-card">
                    <div class="card-body">
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Artist/Band</th>
                                        <th>Album Title</th>
                                        <th>Price</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in products  %}
                                    <tr>

                                        <td>{{ product.artist_name }}</td>
                                        <td>{{ product.album_title }}</td>
                                        <td>£{{ product.get_price }}</td>
                                        <td class="actions-section">
                                            <a href="{{ product.get_update_url }}" class="product-update-btn mr-2"
                                                href="#">Update</a>
                                            <a tabindex="0" class="product-delete-btn" role="button" data-html="true"
                                                data-toggle="popover" data-trigger="focus" title="Are You Sure?"
                                                data-content="<a href='{{ product.get_delete_url }}'>Yes</a>">
                                                Destroy
                                            </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3">
                                            No products to display
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range  %}

                                        {% if page_obj.number == i %}
                                        <li class="active">
                                            <span>
                                                {{i}}
                                                <span class="sr-only">(current)</span>
                                            </span>
                                        </li>
                                        {% else %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>

                                        {% endif %}


                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block scripts %}

<script>
    $(function () {
        $('[data-toggle=popover]').popover();
    })
</script>

{% endblock scripts %}

templates/staff/product_update.html
{% extends "no_header_base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="site-section">
    <div class="container">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Back to Staff Portal</a>
                <hr >
                <h4>Update Product</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="destroy-btn">Update</button>
                </form>
            </div>
    </div>

    {% endblock content %}

templates/staff/staff.html
{% extends "no_header_base.html" %}


{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff portal</h2>
                <div class="card recent-orders-card">
                    <div class="card-body">
                        <h5 class="current-user-email">{{ request.user.email }}
                        </h5>
                        <hr />
                        <a class="inventory-btn flexed" href="{% url 'staff:product-list' %}">
                            View Inventory
                        </a>
                        <hr />
                        <h5 class="customer-orders-text">Recent Customer Orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Refrence No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders  %}
                                    <tr>
                                        <td><a
                                                href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a>
                                        </td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.user.email }}</td>
                                        <td>£{{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not Paid!{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">
                                            You have no orders to show
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range  %}

                                        {% if page_obj.number == i %}
                                        <li class="active">
                                            <span>
                                                {{i}}
                                                <span class="sr-only">(current)</span>
                                            </span>
                                        </li>
                                        {% else %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>

                                        {% endif %}


                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}